---
- hosts: web
  become: yes
  roles:
    - role_web

- hosts: db
  become: yes
  roles:
    - role: spooked03.ansible-role-db
      vars:
        db_name: "{{ hostvars[inventory_hostname]['db_name'] }}"
